### ISSUE TITLE
preinstall msmtp

### ISSUE THREAD

**Issue by schildbach** [instrumentisto/opendmarc-docker-image#9]
In order to send reports, opendmarc needs a sendmail implementation. Currently there is none.

I'd recommend preinstalling msmtp to the docker images, as this can do TLS and SMTP-AUTH.

https://wiki.debian.org/msmtp
https://manpages.debian.org/bookworm/msmtp/msmtp.1.en.html

**Comment by tyranron** [comment]
@schildbach is there any examples of how it's used with OpenDMARC?

**Comment by schildbach** [comment]
I think for simple failure reports all you need to do is enable `FailureReports = true` and optionally customize `ReportCommand`, `FailureReportsBcc`, `FailureReportsOnNone` and `FailureReportsSentBy`. Then in `/etc/ssmtp/ssmtp.conf` you'd configure the MTA to use for sending the report, and likely TLS and SMTP-AUTH.

If you're interested, I could try it out for the Debian-based image and submit a small PR.

**Comment by tyranron** [comment]
@schildbach yes, that would be nice!

**Comment by schildbach** [comment]
I'm changing this proposal from sSMTP to msmtp. Msmtp is much more feature-rich and straightforward to configure, and sSMTP isn't maintained any more.

**Comment by tyranron** [comment]
@schildbach go ahead
